# Generated by Django 5.2 on 2025-05-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="specialist", name="password",),
        migrations.RemoveField(model_name="student", name="password",),
    ]
