# Generated by Django 5.2 on 2025-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_specialist_password_remove_student_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"verbose_name_plural": "Universities",},
        ),
        migrations.RemoveField(model_name="accommodation", name="university",),
        migrations.AddField(
            model_name="accommodation",
            name="universities",
            field=models.ManyToManyField(
                related_name="accommodations", to="api.university"
            ),
        ),
    ]
